spring:
  application:
    name: College-Rest-API
    
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: root
    url: jdbc:h2:mem:suryacolleges;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
      path: /h2-console

    
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
       
    
server:
  port: 8083
  shutdown: graceful





management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        
        
        
    
    
student:
  pageSize: 20
  jwt:
    issuer: "college"
    expireInseconds: 604800
    secretKey: "suryavssurya"
  openApi:
    title: "Student Rest API"
    description: "Student Rest API Swagger Documentation"
    version: "v1.0.0"
    contact:
      name: "Surya"
      email: "isurya@gmail.com"

  
  

